# -*- coding: utf-8 -*-
"""Copy of day1shadil.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIkUw3d15u8E3uIx-hqvoQrU_0KuueIm
"""

class Calculator:
    def _init_(self):
        pass

    def calculate(self, expression):
        operators = set('+-*/')
        # Split the expression into operands and operators
        parts = expression.split()
        # Check if the expression has the correct format
        if len(parts) % 2 == 0 or any(char not in operators and not char.isdigit() for char in expression):
            return "Invalid expression!"

        try:
            result = eval(expression)
            return result
        except Exception as e:
            return "Error: " + str(e)

# Create an instance of the Calculator class
calc = Calculator()



# Function to check if the user wants to try again
def try_again():
    choice = input("Do you want to try again? (yes/no): ")
    return choice.lower() == 'yes'



# Main loop to perform calculations
while True:
    # Take user input for the mathematical expression
    expression = input("Enter a mathematical expression:")

    # Perform the calculation
    result = calc.calculate(expression)
    print("Result:", result)

    # Ask if the user wants to try again
    if not try_again():
      print("goodbye")
      break
